# Generated by Django 3.2.9 on 2021-12-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=200)),
                ('Specialisation', models.CharField(max_length=100)),
                ('Degree_name', models.CharField(max_length=100)),
                ('Internship', models.CharField(max_length=100)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
                ('Gender', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active')], default='Inactive', max_length=20)),
            ],
        ),
    ]
