# Generated by Django 3.2.9 on 2021-12-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='note',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='students',
            name='Gender',
            field=models.CharField(max_length=50),
        ),
    ]
